platform :ios, '12.0'
use_frameworks!

project 'DigitalInkRecognitionExample.xcodeproj'

pod 'GoogleMLKit/DigitalInkRecognition', '3.2.0'
pod 'Sourceful'

target 'DigitalInkRecognitionExample' do
end

target 'DigitalInkRecognitionExampleObjC' do
end
